TypingBook/Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using TypingBook.Extensions;
using TypingBook.Helpers;
using TypingBook.Models;
using TypingBook.Repositories.IReporitories;
using TypingBook.Services;
using TypingBook.ViewModels.Book;
using TypingBook.ViewModelsBuilders.Book;

namespace TypingBook.Controllers
{
    public class BookController : BaseController
    {
        readonly IBookRepository _bookRepository;
        readonly IUserDataRepository _userDataRepository;

        public BookController(IBookRepository bookRepository, IUserDataRepository userDataRepository)
            => (_bookRepository, _userDataRepository) = (bookRepository, userDataRepository);

        [HttpGet]
        public IActionResult Index(string bookOrAuthorSearchString, int? genreFilter)
        {
            var bookViewModelBuilder = new BookViewModelBuilder(_bookRepository,
                                                                _userDataRepository,
                                                                GetLoggedUserId(),
                                                                IsLoggerdUserAdministrator(),
                                                                bookOrAuthorSearchString,
                                                                genreFilter);

            // TODO - if ajax load partial view like in Home/Index
            return View(bookViewModelBuilder.Build());            
        }                

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            var model = new BookRowViewModel();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create(BookRowViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var bookService = new BookContentService();

            model.ContentBeforeModification = model.Content;

            try
            {
                model.Content = bookService.CreateBookPagesJSON(model.Content);
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;                
                return View(model);
            }

            var sql = new Book
            {
                Authors = model.Authors,
                Content = model.Content,
                Genre = model.Genre?.Sum(),
                Description = model.Description,
                Title = model.Title,
                ReleaseDate = model.ReleaseDate.HasValue ? model.ReleaseDate : null,
                AddDate = DateTime.UtcNow,
                License = model.License,
                IsVerified = false,
                UserId = GetLoggedUserId(),
                ContentBeforeModifying = model.ContentBeforeModification
            };

            _bookRepository.CreateBook(sql);
            _bookRepository.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult RebuildBookPages(int id)
        {
            if (id == null)
                return RedirectToAction("Index");

            var book = _bookRepository.GetBookByID(id);
            if (book == null && string.IsNullOrEmpty(book.ContentBeforeModifying) && book.IsVerified)
                return RedirectToAction("Index");//todo show info

            var bookService = new BookContentService();
            book.Content = bookService.CreateBookPagesJSON(book.ContentBeforeModifying);
            _bookRepository.SaveChanges();

            return RedirectToAction("Index");//TODO REDIRECT TO RETRUN URL
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]//todo - mozesz edytowac tylko swoje ksiazki chyba ze jestes adminem, to wszystkie - jesli nie jestes uzytkownikiem - nic nie mozesz
        public IActionResult Edit(int id) 
        {
            var sql = _bookRepository.GetBookByID(id);

            if (sql == null)
                return RedirectToAction("Index");

            var enumConv = EnumBinarySumConverterHelper.GetInstance();

            var model = new BookRowViewModel
            {
                ID = sql.Id,
                Title = sql.Title,
                Description = sql.Description,
                Content = sql.Content,
                ContentInBookPages = JsonSerializer.Deserialize<List<string>>(sql.Content),//edytowanie nic nie da bo prześlesz i tak content
                Genre = sql.Genre.HasValue ? sql.Genre.Value.ConvertEnumSumToIntArray().ToList() : null,
                Authors = sql.Authors,
                Rate = sql.Rate,
                ReleaseDate = sql.ReleaseDate,
                AddDate = sql.AddDate,
                IsVerified = sql.IsVerified,
                License = sql.License,
                UserId = sql.UserId,
                ContentBeforeModification = sql.ContentBeforeModifying
            };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(BookRowViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var sql = _bookRepository.GetBookByID(model.ID);

            var bookService = new BookContentService();

            sql.Content = bookService.CreateBookPagesJSON(model.Content);
            sql.Authors = model.Authors;
            sql.ReleaseDate = model.ReleaseDate;
            sql.Title = model.Title;
            sql.Genre = model.Genre.Sum();

            _bookRepository.UpdateBook(sql);
            _bookRepository.SaveChanges();

            return RedirectToAction("Index");
        }
                
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var book = await _bookRepository.GetAsyncBookByID(id.Value);

            if (book == null)
                return NotFound();

            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var book = await _bookRepository.GetAsyncBookByID(id);
            _bookRepository.RemoveBook(book);
            await _bookRepository.SaveAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> VerifyBook(int id)
        {
            var book = await _bookRepository.GetAsyncBookByID(id);
            book.IsVerified = true;
            await _bookRepository.SaveAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

TypingBook/Controllers/StatisticController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using TypingBook.Services.IServices;
using TypingBook.ViewModels.Statistic;

namespace TypingBook.Controllers
{
    public class StatisticController : BaseController
    {
        private readonly IStatisticService _statisticsService;

        public StatisticController(IStatisticService statisticsService)
            => (_statisticsService) = (statisticsService);

        public IActionResult Index()
        {
            var userId = GetLoggedUserId();

            if (string.IsNullOrEmpty(userId))
                return NotFound();

            var allStats = _statisticsService.GetUserDataById(userId);
            var lastThreeMonthsStats = allStats.OrderByDescending(x => x.date).Take(3);

            var monthlyStatistic = new List<MonthlyStatisticViewModel>();

            if (lastThreeMonthsStats.Any())
            {
                monthlyStatistic.Add(new MonthlyStatisticViewModel() 
                { 
                    Date = lastThreeMonthsStats.First().date,
                    TypedCorrect = lastThreeMonthsStats.First().typedCorrect,
                    TypedWrong = lastThreeMonthsStats.First().typedWrong
                });

                if (lastThreeMonthsStats.Count() >= 2)
                {
                    monthlyStatistic.Add(new MonthlyStatisticViewModel()
                    {
                        Date = lastThreeMonthsStats.ElementAt(1).date,
                        TypedCorrect = lastThreeMonthsStats.ElementAt(1).typedCorrect,
                        TypedWrong = lastThreeMonthsStats.ElementAt(1).typedWrong
                    });
                }

                if (lastThreeMonthsStats.Count() == 3)
                {
                    monthlyStatistic.Add(new MonthlyStatisticViewModel()
                    {
                        Date = lastThreeMonthsStats.Last().date,
                        TypedCorrect = lastThreeMonthsStats.Last().typedCorrect,
                        TypedWrong = lastThreeMonthsStats.Last().typedWrong
                    });
                }
            }

            var model = new StatisticViewModel() 
            { 
                TypedCorrect = allStats.Sum(x => x.typedCorrect),
                TypedWrong = allStats.Sum(x => x.typedWrong),
                MonthlyStatistic = monthlyStatistic
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult SaveData(int typedCorrect, int typedWrong, int millisecondsOfTyping)
        {
            var userId = GetLoggedUserId();

            if (string.IsNullOrEmpty(userId))
                return NotFound();

            _statisticsService.SaveDataByUserId(userId, typedCorrect, typedWrong, millisecondsOfTyping);

            return Ok();
        }
    }
}

TypingBook/Controllers/TypingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Caching.Memory;
using System.Configuration;
using TypingBook.Data;
using TypingBook.Repositories.IReporitories;
using TypingBook.Services.IServices;
using TypingBook.ViewModels.Typing;

namespace TypingBook.Controllers
{
    public class TypingController : BaseController
    {
        readonly IUserDataRepository _userDataRepository;
        readonly IBookRepository _bookRepository;
        readonly IMemoryCache _memoryCache;
        readonly ITypingServices _typingServices;

        public TypingController(IUserDataRepository userDataRepository, IBookRepository bookRepository, ITypingServices typingServices, IMemoryCache memoryCache)
        {
            _userDataRepository = userDataRepository;
            _bookRepository = bookRepository;
            _memoryCache = memoryCache;
            _typingServices = typingServices;
        }

        
        [HttpGet]
        public IActionResult Index(int? bookId, int? currentBookPage)
        {
            var result = new TypingViewModel();
            var userId = GetLoggedUserId();
            
            result = _typingServices.GetTypingViewModel(userId, bookId, currentBookPage);

            if (result == null)
                return RedirectToAction("Index","Book");
            
            bool isAjaxCall = Request.Headers["x-requested-with"] == "XMLHttpRequest";

            if (isAjaxCall)
                return PartialView("_Index", result);
            else
                return View(result);
        }


        [HttpPost]
        [Authorize]
        public IActionResult SaveTypingResult(int bookId, int nextBookPage, int correctTyped, int wrongTyped)//bookId pokazuje jakby currentPage+1, nextBookPage jest undifined..
        {
            var userId = GetLoggedUserId();
            
            if (string.IsNullOrEmpty(userId))
                return BadRequest();

            var result = _typingServices.SaveBookProgress(bookId, nextBookPage, userId);  
            return Ok(result);
        }
    }
}

TypingBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TypingBook</title>

    @*<environment include="Development">*@
    @if (true)
    {
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-darkly.css" />
    }
    else
    {
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    }
    @*</environment>*@
    @*<environment exclude="Development">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                  crossorigin="anonymous"
                  integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
        </environment>*@
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.highcharts.com/highcharts.js"></script>
</head>
<body>
    <div class="progress bg-light" style="height:5px">
        <div id="progress-bar-correct" class="progress-bar bg-info progress-bar-animated" role="progressbar" style="width: 0%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
        <div id="progress-bar-wrong" class="progress-bar bg-danger progress-bar-animated" role="progressbar" style="width: 0%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
    </div>

    <header>
        <partial name="_MainMenuPartial" />
    </header>

    <div class="container body-container">
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="alert alert-danger" role="alert">@Html.Raw(@TempData["ErrorMessage"].ToString())</div>
                </div>
            </div>
        }

        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        ajaxLink();
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

TypingBook/Views/Shared/_MainMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@if (true)
{
    @Html.Raw("<nav class=\"navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark\">")

}
else
{
    @Html.Raw("<nav class=\"navbar navbar - expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3\">")

}


<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>

<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
    <partial name="_LoginPartial" />

    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link" asp-action="Index" asp-controller="Typing">Type!</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-action="Index" asp-controller="Book">Books</a>
        </li>
        @if (User.Identity.IsAuthenticated)
        {
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Statistic">Statistic</a>
            </li>
        }
        <li class="nav-item">
            <a class="nav-link" asp-action="Privacy" asp-controller="Home">Privacy</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled">app version: Beta 0.7 (early development)</a>
        </li>
        @if (User.IsInRole("Administrator"))
        {
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Administrator">AdminPanel</a>
            </li>
        }
        <li>
            <div id="alterPlaceholder" class="alert alert-primary" style="display: none;"></div>
        </li>
    </ul>
</div>


@Html.Raw("</nav>")

TypingBook/Views/Shared/_ModalLayout.cshtml
<div class="modal fade" id="mainModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    Modal title
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
                    @RenderBody()
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Save changes</button>
                <button type="button" class="btn btn-secondary" datadismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>